FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 5000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

# Use Node.js LTS image

# FROM node:20

# # Set working directory
# WORKDIR /app

# # Copy package files and install dependencies
# COPY package*.json ./
# RUN npm install

# # Copy source code
# COPY . .

# # Build if using TypeScript
# RUN npm run build

# # Expose backend port
# EXPOSE 5000

# # Start the app
# CMD ["node", "dist/index.js"]